
CREATE SCHEMA PWS;

SET CURRENT SCHEMA PWS;

CREATE TABLE ACTIVITY
(
  ID BIGINT PRIMARY KEY NOT NULL,
  ACTION VARCHAR(255) NOT NULL,
  CREATED TIMESTAMP NOT NULL,
  FACILITY INT NOT NULL,
  REMOTE VARCHAR(255) NOT NULL,
  RESULT VARCHAR(255),
  SEVERITY INT NOT NULL,
  SOURCE VARCHAR(255) NOT NULL,
  SOURCE_INFO VARCHAR(255)
);
CREATE TABLE CERTIFICATE
(
  ID BIGINT PRIMARY KEY NOT NULL,
  APP_ID VARCHAR(255),
  DISABLED SMALLINT,
  OS VARCHAR(255),
  SHARED_SECRET VARCHAR(255),
  VENDOR VARCHAR(255),
  VERSION VARCHAR(255)
);
CREATE TABLE CREDENTIALS
(
  ID BIGINT PRIMARY KEY NOT NULL,
  IP VARCHAR(255) NOT NULL,
  MAC VARCHAR(255),
  PASSWORD VARCHAR(255),
  USERNAME VARCHAR(255) NOT NULL
);
CREATE TABLE CREDENTIALS_ENCODER
(
  ENCODER_TYPE VARCHAR(31) NOT NULL,
  ID BIGINT PRIMARY KEY NOT NULL
);
CREATE TABLE CREDENTIALS_MODIFIER
(
  ID BIGINT PRIMARY KEY NOT NULL,
  POSITION INT NOT NULL,
  TARGET INT NOT NULL,
  VALUE VARCHAR(255) NOT NULL
);
CREATE TABLE RADIUS
(
  ID BIGINT PRIMARY KEY NOT NULL,
  ADDRESS VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PORT INT NOT NULL,
  SHARED_SECRET VARCHAR(255) NOT NULL
);
CREATE TABLE CREDENTIALS_TRANSLATION
(
  ID BIGINT PRIMARY KEY NOT NULL,
  AUTHENTICATE_WITH_DOMAIN SMALLINT NOT NULL,
  ENCODER_VALUE VARCHAR(255),
  ENCODER_ID BIGINT,
  CONSTRAINT FKIHU659OJE65CDKKF648K4BOI FOREIGN KEY (ENCODER_ID) REFERENCES CREDENTIALS_ENCODER (ID)
);
CREATE TABLE NAS
(
  TYPE VARCHAR(31) NOT NULL,
  ID BIGINT PRIMARY KEY NOT NULL,
  IPV4_ADDRESS VARCHAR(255),
  IPV6_ADDRESS VARCHAR(255),
  NAME VARCHAR(255) NOT NULL,
  AUTHENTICATION_TYPE VARCHAR(255),
  LISTEN_PORT INT,
  PORTAL_SHARED_SECRET VARCHAR(255),
  VERSION VARCHAR(255),
  NPS_TYPE INT,
  NPS_SHARED_SECRET VARCHAR(255),
  TRANSLATION_ID BIGINT,
  CONSTRAINT FKP0LQUFTEGXPXGN28Q4GY5273O FOREIGN KEY (TRANSLATION_ID) REFERENCES CREDENTIALS_TRANSLATION (ID)
);
CREATE TABLE NAS_RADIUS
(
  NAS_ID BIGINT NOT NULL,
  RADIUS_ID BIGINT NOT NULL,
  CONSTRAINT FK17GS5H4F8NA9DVD9LHU7V5EWG FOREIGN KEY (NAS_ID) REFERENCES NAS (ID),
  CONSTRAINT FK2ETB5OLWE12UTR2CJDGQ2LIRD FOREIGN KEY (RADIUS_ID) REFERENCES RADIUS (ID)
);
CREATE TABLE NAS_RULE
(
  RULE_TYPE VARCHAR(31) NOT NULL,
  ID BIGINT PRIMARY KEY NOT NULL,
  IPV4_END VARCHAR(255) NOT NULL,
  IPV4_START VARCHAR(255) NOT NULL,
  SUPPORTED_DOMAINS VARCHAR(255),
  NAS_ID BIGINT,
  CONSTRAINT FKRHIIIYM0QJLSCRU8ECBSHQHS0 FOREIGN KEY (NAS_ID) REFERENCES NAS (ID)
);
CREATE TABLE SESSION
(
  ID BIGINT PRIMARY KEY NOT NULL,
  START_DATE TIMESTAMP,
  CERTIFICATE_ID BIGINT,
  CREDENTIALS_ID BIGINT,
  NAS_ID BIGINT,
  CONSTRAINT FKM467WYMH71RFJDLCU3Y2SED4R FOREIGN KEY (CERTIFICATE_ID) REFERENCES CERTIFICATE (ID),
  CONSTRAINT FK8RS04XFXBNSY7J4POL1WJTBPI FOREIGN KEY (CREDENTIALS_ID) REFERENCES CREDENTIALS (ID),
  CONSTRAINT FKJ2S5K51FBY8NJ6T258DCWMJV3 FOREIGN KEY (NAS_ID) REFERENCES NAS (ID)
);
CREATE TABLE TRANSLATION_MODIFIER
(
  TRANS_ID BIGINT NOT NULL,
  MOD_ID BIGINT NOT NULL,
  CONSTRAINT FK3VCJTXIFWYJI7KBDCPG4EMD27 FOREIGN KEY (MOD_ID) REFERENCES CREDENTIALS_MODIFIER (ID),
  CONSTRAINT FKIIE289KLBB6RIJI5SJOXKU8FO FOREIGN KEY (TRANS_ID) REFERENCES CREDENTIALS_TRANSLATION (ID)
);