CREATE SCHEMA PWS;

CREATE TABLE PWS.ACTIVITY
(
  ID BIGINT PRIMARY KEY NOT NULL,
  ACTION VARCHAR(255) NOT NULL,
  CREATED TIMESTAMP NOT NULL,
  FACILITY INT NOT NULL,
  REMOTE VARCHAR(255) NOT NULL,
  RESULT VARCHAR(255),
  SEVERITY INT NOT NULL,
  SOURCE VARCHAR(255) NOT NULL,
  SOURCE_INFO VARCHAR(255)
);
CREATE TABLE PWS.CERTIFICATE
(
  ID BIGINT PRIMARY KEY NOT NULL,
  APP_ID VARCHAR(255),
  DISABLED SMALLINT,
  OS VARCHAR(255),
  SHARED_SECRET VARCHAR(255),
  VENDOR VARCHAR(255),
  VERSION VARCHAR(255)
);
CREATE TABLE PWS.CREDENTIALS
(
  ID BIGINT PRIMARY KEY NOT NULL,
  IP VARCHAR(255) NOT NULL,
  MAC VARCHAR(255),
  PASSWORD VARCHAR(255),
  USERNAME VARCHAR(255) NOT NULL
);
CREATE TABLE PWS.CREDENTIALS_ENCODER
(
  ENCODER_TYPE VARCHAR(31) NOT NULL,
  ID BIGINT PRIMARY KEY NOT NULL
);
CREATE TABLE PWS.CREDENTIALS_MODIFIER
(
  ID BIGINT PRIMARY KEY NOT NULL,
  POSITION INT NOT NULL,
  TARGET INT NOT NULL,
  VALUE VARCHAR(255) NOT NULL
);
CREATE TABLE PWS.CREDENTIALS_TRANSLATION
(
  ID BIGINT PRIMARY KEY NOT NULL,
  AUTHENTICATE_WITH_DOMAIN SMALLINT NOT NULL,
  ENCODER_VALUE VARCHAR(255),
  ENCODER_ID BIGINT,
  CONSTRAINT FKIHU659OJE65CDKKF648K4BOI FOREIGN KEY (ENCODER_ID) REFERENCES CREDENTIALS_ENCODER (ID)
);
CREATE TABLE PWS.NAS
(
  ID BIGINT PRIMARY KEY NOT NULL,
  IPV4_ADDRESS VARCHAR(255),
  IPV6_ADDRESS VARCHAR(255),
  NAME VARCHAR(255) NOT NULL,
  TYPE INT NOT NULL,
  TRANSLATION_ID BIGINT,
  CONSTRAINT FKP0LQUFTEGXPXGN28Q4GY5273O FOREIGN KEY (TRANSLATION_ID) REFERENCES CREDENTIALS_TRANSLATION (ID)
);
CREATE TABLE PWS.NAS_RULE
(
  RULE_TYPE VARCHAR(31) NOT NULL,
  ID BIGINT PRIMARY KEY NOT NULL,
  IPV4_END VARCHAR(255) NOT NULL,
  IPV4_START VARCHAR(255) NOT NULL,
  SUPPORTED_DOMAINS VARCHAR(255),
  NAS_ID BIGINT,
  CONSTRAINT FKRHIIIYM0QJLSCRU8ECBSHQHS0 FOREIGN KEY (NAS_ID) REFERENCES NAS (ID)
);
CREATE TABLE PWS.SESSION
(
  ID BIGINT PRIMARY KEY NOT NULL,
  START_DATE TIMESTAMP,
  CERTIFICATE_ID BIGINT,
  CREDENTIALS_ID BIGINT,
  NAS_ID BIGINT,
  CONSTRAINT FKM467WYMH71RFJDLCU3Y2SED4R FOREIGN KEY (CERTIFICATE_ID) REFERENCES CERTIFICATE (ID),
  CONSTRAINT FK8RS04XFXBNSY7J4POL1WJTBPI FOREIGN KEY (CREDENTIALS_ID) REFERENCES CREDENTIALS (ID),
  CONSTRAINT FKJ2S5K51FBY8NJ6T258DCWMJV3 FOREIGN KEY (NAS_ID) REFERENCES NAS (ID)
);
CREATE TABLE PWS.TRANSLATION_MODIFIER
(
  TRANS_ID BIGINT NOT NULL,
  MOD_ID BIGINT NOT NULL,
  CONSTRAINT FK3VCJTXIFWYJI7KBDCPG4EMD27 FOREIGN KEY (MOD_ID) REFERENCES CREDENTIALS_MODIFIER (ID),
  CONSTRAINT FKIIE289KLBB6RIJI5SJOXKU8FO FOREIGN KEY (TRANS_ID) REFERENCES CREDENTIALS_TRANSLATION (ID)
);