
SET CURRENT SCHEMA PWS;

ALTER TABLE TRANSLATION_MODIFIER DROP CONSTRAINT FK3VCJTXIFWYJI7KBDCPG4EMD27;
ALTER TABLE TRANSLATION_MODIFIER DROP CONSTRAINT FKIIE289KLBB6RIJI5SJOXKU8FO;

ALTER TABLE CREDENTIALS_TRANSLATION DROP CONSTRAINT FKIHU659OJE65CDKKF648K4BOI;

ALTER TABLE NAS_RULE DROP CONSTRAINT FKRHIIIYM0QJLSCRU8ECBSHQHS0;
ALTER TABLE NAS DROP CONSTRAINT FKP0LQUFTEGXPXGN28Q4GY5273O;

ALTER TABLE NAS_RADIUS DROP CONSTRAINT FK2ETB5OLWE12UTR2CJDGQ2LIRD;
ALTER TABLE NAS_RADIUS DROP CONSTRAINT FK17GS5H4F8NA9DVD9LHU7V5EWG;

ALTER TABLE SESSION DROP CONSTRAINT FKM467WYMH71RFJDLCU3Y2SED4R;
ALTER TABLE SESSION DROP CONSTRAINT FKJ2S5K51FBY8NJ6T258DCWMJV3;
ALTER TABLE SESSION DROP CONSTRAINT FK8RS04XFXBNSY7J4POL1WJTBPI;

SET CURRENT SCHEMA PWS;

DROP TABLE ACTIVITY;
DROP TABLE CERTIFICATE;
DROP TABLE RADIUS;
DROP TABLE CREDENTIALS;
DROP TABLE CREDENTIALS_ENCODER;
DROP TABLE CREDENTIALS_MODIFIER;
DROP TABLE TRANSLATION_MODIFIER;
DROP TABLE CREDENTIALS_TRANSLATION;
DROP TABLE NAS_RADIUS;
DROP TABLE NAS_RULE;
DROP TABLE NAS;
DROP TABLE 'SESSION';

DROP SCHEMA PWS RESTRICT ;